FileOperationApp/Controllers/TextParserController.cs
using FileOperationApp.Models;
using FileOperationApp.Views.TextParser;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace FileOperationApp.Controllers
{
    public class TextParserController : Controller
    {
        // GET: TextParser
        public ActionResult Index()
        {
            TextParserViewModel loTextParserViewModel = new TextParserViewModel();
            ViewBag.directoryFiles = Directory.GetFiles(Server.MapPath(Constants.FilePath));
            return View();
        }

        [HttpPost]
        public ActionResult Index(TextParserViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                #region Save File
                HttpPostedFileBase postedFile = viewModel.file;

                if (postedFile != null && postedFile.ContentLength > 0)
                {        
                    string fileName = Path.GetFileName(postedFile.FileName);        
                    string path = Path.Combine(Server.MapPath(Constants.FilePath), fileName);
                    int count = 1;

                    while (System.IO.File.Exists(path))
                    {
                        string tempFileName = string.Format("{0}({1})", Path.GetFileNameWithoutExtension(postedFile.FileName), count++);
                        path = Path.Combine(Server.MapPath(Constants.FilePath), tempFileName + Path.GetExtension(postedFile.FileName));
                    }
                    postedFile.SaveAs(path);

                    TempData["Success"] = "File " + Path.GetFileName(path) + " uploaded successfully!";

                }
                #endregion
            }            
            ViewBag.directoryFiles = Directory.GetFiles(Server.MapPath(Constants.FilePath));
            return View(viewModel);
        }

        [HttpGet]
        public string GetContentFromFile(string fileName, int startingLine, int endingLine)
        {
            string fileFullPath = Path.Combine(Server.MapPath(Constants.FilePath), fileName);
            string content = string.Empty;

            int lineIndex = 1;
            using (StreamReader r = new StreamReader(fileFullPath))
            {
                string line = string.Empty;

                while ((line = r.ReadLine()) != null)
                {
                    if (lineIndex >= startingLine && lineIndex <= endingLine)
                    {
                        content += line + Environment.NewLine;
                    }

                    lineIndex++;
                }
                    
            }

            return content;
        }

        [HttpGet]
        public int GetFileTotalLines(string fileName)
        {
            string fileFullPath = Path.Combine(Server.MapPath(Constants.FilePath), fileName);
            var lineCount = 0;
            using (var reader = System.IO.File.OpenText(fileFullPath))
            {
                while (reader.ReadLine() != null)
                {
                    lineCount++;
                }
            }

            return lineCount;
        }

        [HttpPost]
        public JsonResult SubmitCommand(string fileName, string commandText)
        {            
            List<FileOutputResult> resultList = new List<FileOutputResult>();            

            string[] commands = commandText.Split(Constants.NewLine);

            ProcessCommandLineByLine(fileName, commands, resultList);
            
            return Json(resultList);            
        }

        private void ProcessCommandLineByLine(string fileName, string[] commands, List<FileOutputResult> resultList)
        {            
            foreach (string command in commands)
            {
                try
                {
                    if (string.IsNullOrEmpty(command.Trim()))
                    {
                        continue;
                    }

                    IdentifyCommand(fileName, command, resultList);                    
                }
                catch (Exception ex)
                {
                    FileOutputResult fileOutputResult = new FileOutputResult();
                    fileOutputResult.isValid = false;
                    fileOutputResult.message = "Error in command - " + command;
                    //fileOutputResult.newContent = "";

                    resultList.Add(fileOutputResult);
                }
            }
        }
        private void IdentifyCommand(string fileName, string command, List<FileOutputResult> resultList)
        {   
            string trimmedCommand = command.Trim().Replace(Constants.SpaceString, string.Empty);

            switch (trimmedCommand[0])
            {
                case 's':
                    ParseAndReplace(fileName, command, trimmedCommand);
                    break;
                case 'd':
                    ParseAndDelete(fileName, command, trimmedCommand);
                    break;
                case 'i':
                    ParseAndInsert(fileName, command, trimmedCommand);
                    break;
                case 'r':
                    ParseAndReverse(fileName, command, trimmedCommand);
                    break;
                default:
                    throw new InvalidCommand("Invalid command");
                    //break;
            }

            FileOutputResult fileOutputResult = new FileOutputResult();
            fileOutputResult.isValid = true;
            fileOutputResult.message = string.Empty;
            //fileOutputResult.newContent = "";

            resultList.Add(fileOutputResult);
        }

        private void ParseAndReplace(string fileName, string command, string trimmedCommand)
        {
            if (trimmedCommand.StartsWith("sr"))
            {
                string secParam = string.Empty;
                string thirdParam = string.Empty;
                int lineNo = 0;
                string lineNoStr = string.Empty;

                switch (trimmedCommand[2])
                {
                    case Constants.SingleQuote:
                        if (trimmedCommand[2] == Constants.SingleQuote && trimmedCommand[4] == Constants.SingleQuote &&
                                        trimmedCommand[5] == Constants.SingleQuote && trimmedCommand[7] == Constants.SingleQuote
                                        ) //For char
                        {
                            secParam = trimmedCommand[3].ToString();
                            thirdParam = trimmedCommand[6].ToString();

                            if (secParam.Length == 1 && thirdParam.Length == 1)
                            {
                                lineNo = 0;
                                lineNoStr = trimmedCommand.Substring(trimmedCommand.LastIndexOf(Constants.SingleQuote) + 1);

                                if (!string.IsNullOrEmpty(lineNoStr))
                                    lineNo = Convert.ToInt32(lineNoStr);

                                ReplaceLine(fileName, secParam[0], thirdParam[0], lineNo);
                            }
                            else
                                throw new InvalidCommand("Invalid Parameters");

                        }
                        else
                            throw new InvalidCommand("Invalid Parameters");
                        break;
                    case Constants.DoubleQuote:
                        
                        string trimString = command.Substring(command.IndexOf(Constants.DoubleQuoteString) + 1);
                        secParam = trimString.Substring(0, trimString.IndexOf(Constants.DoubleQuoteString));

                        trimString = trimString.Substring(trimString.IndexOf(Constants.DoubleQuoteString) + 1);

                        trimString = trimString.Substring(trimString.IndexOf(Constants.DoubleQuoteString) + 1);
                        thirdParam = trimString.Substring(0, trimString.IndexOf(Constants.DoubleQuoteString));

                        lineNo = 0;
                        lineNoStr = trimmedCommand.Substring(trimmedCommand.LastIndexOf(Constants.DoubleQuoteString) + 1);

                        if (!string.IsNullOrEmpty(lineNoStr))
                            lineNo = Convert.ToInt32(lineNoStr);

                        ReplaceLine(fileName, secParam, thirdParam, lineNo);
                        
                        break;
                    default:
                        throw new InvalidCommand("Invalid Parameters");
                }
            }
            else
            {
                throw new InvalidCommand("Invalid command");
            }
        }
        private void ParseAndDelete(string fileName, string command, string trimmedCommand)
        {
            int lineNo = 0;
            string lineNoStr = trimmedCommand.Substring(1);

            if (!string.IsNullOrEmpty(lineNoStr))
                lineNo = Convert.ToInt32(lineNoStr);

            if (lineNo > 0) 
            {
                #region Delete                
                DeleteLine(fileName, lineNo);
                #endregion
            }
            else
            {
                throw new InvalidCommand("Invalid Parameters");
            }
        }
        private void ParseAndInsert(string fileName, string command, string trimmedCommand)
        {
            int lineNo = 0;
            string lineNoStr = trimmedCommand.Substring(1, trimmedCommand.IndexOf(Constants.DoubleQuoteString) - 1);

            if (!string.IsNullOrEmpty(lineNoStr) && trimmedCommand[trimmedCommand.Length - 1] == Constants.DoubleQuote)
                lineNo = Convert.ToInt32(lineNoStr);

            if (lineNo > 0)
            {
                string trimString = command.Substring(command.IndexOf(Constants.DoubleQuoteString) + 1);

FileOperationApp/Views/TextParser/Index.cshtml
@model FileOperationApp.Views.TextParser.TextParserViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Text Parser</h2>
<style>
    .redfont {
        color: red;
    }

    #loading {
        width: 100%;
        height: 100%;
        top: 0px;
        left: 0px;
        position: fixed;
        display: block;
        opacity: 0.7;
        background-color: #fff;
        z-index: 99;
        text-align: center;
    }

    #loading-image {
        position: absolute;
        top: 260px;
        left: 600px;
        z-index: 100;
    }
</style>

<div id="loading">
    <img id="loading-image" src="~/Content/Image/ajax-loader.gif" alt="Loading..." />    
</div>

    <div style="width:100%">
        <table style="width:100%">
            <tr>
                <td style="vertical-align:top;" >
                    Upload file:
                </td>
                <td>
                    @*@using (Html.BeginForm("Index", "TextParser", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {*@

@using (Html.BeginForm("Index", "TextParser", FormMethod.Post, new { id = "fileuploadform", enctype = "multipart/form-data", onsubmit = "return Validate();" }))
{
                        <input type="file" name="file" id="file" />
                        <div>
                            <input type="submit" value="Upload" />
                        </div>

                        <div id="FileMessage" style="color:red;"></div>
                        @*<span>@Html.ValidationMessageFor(m => m.file, "", new { @class = "redfont"})</span>*@
                    }
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <table>
                        <tr>
                            <td colspan="2">
                                &nbsp;

                                @if (TempData["Success"] != null)
                                {
                                    <p id="filesuccess" style="color:red;">@TempData["Success"]</p>
                                    TempData["Success"] = null;
                                }
                            </td>
                        </tr>
                        <tr>
                            <th align="center">
                                Files
                            </th>
                        </tr>


                        @foreach (string item in ViewBag.directoryFiles)
                        {
                            <tr>
                                <td>
                                    @*@Html.RadioButton("rbgFile", Path.GetFileName(item), false, htmlAttributes: new { onclick = "getFileContent('" + Path.GetFileName(item) + "')" })*@
                                    @Html.RadioButton("rbgFile", Path.GetFileName(item), false, htmlAttributes: new { onclick = "showContent('" + Path.GetFileName(item) + "', false)" })
                                </td>

                                <td>
                                    @Path.GetFileName(item)
                                </td>
                            </tr>
                        }
                        <tr>
                            <th>
                                &nbsp;
                            </th>
                        </tr>

                    </table>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">
                    Content :
                </td>
                <td>
                    @Html.TextAreaFor(model => model.Content, 10, 150, null)
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">
                    Command :
                </td>
                <td>
                    @Html.TextAreaFor(model => model.Command, 5, 150, null)

                    <div><input type="submit" value="Execute Command" id="btnSubmitCommand" style="display:none;" /></div>
                </td>
            </tr>

            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    <div id="msg" style="color:red;display:none"></div>
                </td>
            </tr>

            <tr>
                <td style="vertical-align:top;">
                    Filtered Content :
                </td>
                <td>
                    @Html.TextArea("NewContent", string.Empty, 10, 150, null)
                </td>
            </tr>

        </table>
    </div>

    <script src="~/scripts/jquery-1.10.2.js"></script>
    <script>
        function getFileContent(fileName, startingLine, endingLine, TotalLines, isFilteredContent) {

            $.ajax({
                type: 'GET',
                url: '/TextParser/GetContentFromFile',
                cache: false,
                data: { fileName: fileName, startingLine: startingLine, endingLine: endingLine },
                success: function (content) {
                    
                    if (!isFilteredContent)
                        $('#Content').val($('#Content').val() + content);
                    else 
                        $('#NewContent').val($('#NewContent').val() + content);
                    
                    if (endingLine < TotalLines) {
                        var start = endingLine + 1;
                        var end = (start + 5000 <= TotalLines) ? start + 5000 : TotalLines;

                        getFileContent(fileName, start, end, TotalLines, isFilteredContent);
                    }
                    else {
                        $("#loading").hide();
                    }
                    
                },
                error: function (request) {
                    alert(request.responseText);
                }
            });

        }

        function ShowContentBySequence(fileName, TotalLines, isFilteredContent)
        {
            if (TotalLines > 0) {
                var start = 1;
                var end = (start + 5000 <= TotalLines) ? start + 5000 : TotalLines;

                getFileContent(fileName, start, end, TotalLines, isFilteredContent);
            }
        
        }

        function AppendContent(content) {
            $('#content').text($('#content').text() + content);
        }

        function showContent(fileName, isFilteredContent) {
            $.ajax({
                type: 'GET',
                url: '/TextParser/GetFileTotalLines',
                cache: false,
                data: { fileName: fileName },
                success: function (response) {
                    var TotalLines = parseInt(response);
                    var LastIndex = 0;

                    if (!isFilteredContent) {
                        $('#Content').val("");

                        $("#loading").show();
                        ShowContentBySequence(fileName, TotalLines, isFilteredContent);
                        

                        $('#btnSubmitCommand').show();
                    }
                    else {
                        $('#NewContent').val("");

                        $("#loading").show();
                        ShowContentBySequence(fileName, TotalLines, isFilteredContent);
                        
                    }
                    
                },
            });
        }

        function getNewContent(commandText) {
            $.ajax({
                type: 'POST',
                url: '/TextParser/SubmitCommand',
                cache: false,
                data: { fileName: $("input:radio[name=rbgFile]:checked").val(), commandText: commandText },
                success: function (object) {
                    
                    $("#msg").html('');
                    $("#msg").hide();

                    var isAllFailed = true;
                    //$(object.fileOutputResultList).each(function (i, obj) {
                    $(object).each(function (i, obj) {
                        if (!obj.isValid) {
                            $("#msg").html($("#msg").html() + obj.message + "<br />").show();
                        }
                        else
                        {
                            isAllFailed = false;                            
                        }
                    });

                    if (!isAllFailed)
                        showContent($("input:radio[name=rbgFile]:checked").val(), true);
                },
            });
        }

        $(function () {
            $("#btnSubmitCommand").click(function () {
                if ($('#Command').val().trim() == "") {
                    $("#msg").html("Please enter at least one command").show();
                }
                else
                {
                    $("#msg").html("").hide();
                    $("#loading").hide();
                    getNewContent($('#Command').val());
                }                
            });

            //document.getElementById("file").required = true;
        });

        function Validate() {
            $("#filesuccess").html("");

            var ext = $('#file').val().split('.').pop().toLowerCase();
            if ($.inArray(ext, ['txt']) == -1) {
                $("#FileMessage").html("Please enter file having .txt extension");
                
                return false;
            }
            else {
                $("#FileMessage").html("");
                return true;
            }
        }

        $(function () {
            $("#loading").hide();
        });
    </script>